### PR TITLE
Add System property column

### PR DESCRIPTION
**Pull request by shantanu-vsbhosale**
Goal was to make system properties available to user easily.

### CODE REVIEW

**Comment by jcchavezs** [comment]
Hi @shantanu-vsbhosale thanks for this. Would you please elaborate a bit on what are these properties, where are they going to be used and also update the generator instead as this is autogenerated?

**Comment by shantanu-vsbhosale** [comment]
@jcchavezs 
Only one extra environment variable was added i.e.   **HT_REPORTING_TRACE_TYPE**. This is already part of auto-generation proto file (https://github.com/hypertrace/agent-config/blob/d3d62ccb00d1e857becdd330b02405fd7ab6fd50/config.proto#L56)

Extra column was added for the **system properties** that corresponds to a particular environment variable. Correlation can be found here (https://github.com/hypertrace/javaagent/blob/main/javaagent-core/src/main/java/org/hypertrace/agent/core/config/EnvironmentConfig.java)

**Why required and where will they be used ?** 
 hypertrace java-agent can be started with giving configs in 3 ways (config.yaml file, environment variables,  system properties). We provided the docs for first 2 ways, but little information is available for the 3rd way (system properties).  Open telemetry has documented it very clearly and makes it easy for the user. (https://opentelemetry.io/docs/java/automatic_instrumentation/)

So, the change is just a docs change for ease of java-agent user.

CC: @pavolloffay

**Comment by pavolloffay** [comment]
There is a bit of misunderstanding. I thought that you want to add it to the product docs for javaagent.

Here the system properties do not make much sense bc the config is for all languages and the system props exist only in Java.

**Comment by shantanu-vsbhosale** [comment]
Yes, I misunderstood this. I thought it will be helpful here as well. I was not aware that system properties are only for java. I'll close this.

**Comment by jcchavezs** [comment]
Thanks for the will to improve this documentation anyways!

**Pull request closed without merging**
